# Generated by Django 4.2.4 on 2023-08-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(editable=False, max_length=240, unique=True, verbose_name='Personal Identification Number')),
                ('full_name', models.CharField(max_length=240, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=240, verbose_name='Event Name')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_location', models.CharField(max_length=240, verbose_name='Event Location')),
                ('event_price', models.IntegerField(default=0, verbose_name='Event Price')),
                ('ticket_status', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP'), ('GOLD', 'Gold')], max_length=10, verbose_name='Ticket Status')),
                ('ticket_start_time', models.TimeField(verbose_name='Ticket Start Time')),
                ('ticket_end_time', models.TimeField(verbose_name='Ticket End Time')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_ticketing_bkarena.usertbl')),
            ],
        ),
    ]
